### ISSUE TITLE
Adding object from lib behaves incorrect

### ISSUE THREAD

**Issue by iamyb** [MerrimanInd/drawpyo#22]
Thanks for the repo first.

If I only add with the ellipse, then the page only displays the basic object without ellipse
`item_from_lib = drawpyo.diagram.object_from_library(
    page=page,
    library="general",
    obj_name="ellipse",
    value="ellipse"
    )`

I have to add one more line to make it working.
`item_from_lib.apply_style_string("ellipse;")`

**Comment by MerrimanInd** [comment]
I see, it looks like it's not correctly parsing the `baseStyle` attribute. I'll see if I can get it sorted, thanks!
