### ISSUE TITLE
Example is not working?

### ISSUE THREAD

**Issue by rokdd** [MerrimanInd/drawpyo#32]
I feel very stupid but I am not able to run even the example:

```
import drawpyo
file = drawpyo.File()
```

Gives me:

```
    file = drawpyo.File()
AttributeError: partially initialized module 'drawpyo' has no attribute 'File' (most likely due to a circular import)
```

I just installed drawpyo in version 0.1.3 that should be fine?

**Comment by MerrimanInd** [comment]
Hey @rokdd, I just reran a basic example using the version on pip (also 0.1.3) and it ran fine. Also tried just running:

```
import drawpyo
file = drawpyo.File()
```

and I didn't get an import error. Can you give me some more details about what you're running and in what environment?

**Comment by rokdd** [comment]
I am using python 3.10 in Windows.. What else I can provide you? Like you might noticed I was also wondering that it does not work.. ;-)

**Comment by MerrimanInd** [comment]
I ran my tests and created a File object in Python 3.10 on Linux and still haven't seen the error. If you're using an environment manager try running it in a clean environment, there might be an import conflict. The only imports it could be failing at are built-in libraries which shouldn't be an issue. You can also try pulling the repo and importing from the src folder directly?

**Comment by MerrimanInd** [comment]
Hey @rokdd I just confirmed functionality on Python 3.10 on Windows just to be certain and I still can't reproduce the bug. I suspect it has something to do with your environment/Python install. In about a week I'll close this ticket as unreproduceable if we can't narrow in on it.

**Comment by rokdd** [comment]
Well lets close it.. I will sent you more informations when I will find something out.
