### ISSUE TITLE
Add List and List Item to `general.toml`

### ISSUE THREAD

**Issue by ahron-maslin** [MerrimanInd/drawpyo#33]

**Comment by MerrimanInd** [comment]
FYI I'm still chipping away at this! More to come soon hopefully.

**Comment by ahron-maslin** [comment]
Thanks! In the meantime, I hacked the add_object function to manually set the parent id of the list item to the list container

**Comment by MerrimanInd** [comment]
Version 0.2 is up with the List object! Check out the docs here. Give it a try, let me know if you find any issues or usability tweaks.

https://merrimanind.github.io/drawpyo/usage/extended_objects/
