### ISSUE TITLE
are you aware of a way to convert these diagrams into png through the api?

### ISSUE THREAD

**Issue by bhomass** [MerrimanInd/drawpyo#34]
I know it's not your main goal, biut given you instructed a new structured format, maybe you are far away.

**Comment by MerrimanInd** [comment]
There is a way but it'll be more complicated. Someone else developed a Docker image running drawpyo that offers an export function. I have an open issue to integrate it (someday).

https://github.com/MerrimanInd/drawpyo/issues/29
