### ISSUE TITLE
Update Documentation for creating edges with no arrows (Line Ends)

### ISSUE THREAD

**Issue by lungheichen** [MerrimanInd/drawpyo#44]
I don't believe there's a way to create edges with no arrows for Line Ends. Per the [Edges](https://merrimanind.github.io/drawpyo/usage/edges/) page of the Documentation, there's no value for no arrows for the parameters line_end_target and line_end_source. 

Also, I'm not sure if documentation here is distinguishing between values and parameters properly.

**Comment by lungheichen** [comment]
Nevermind on this. Looks like the way to do it is to use the value "none" (lowercase) to the parameters line_end_target and line_end_source. Could this be put into the documentation, in the Line Ends section?

**Comment by MerrimanInd** [comment]
Hey @lungheichen, absolutely I'll get that in the docs soon. I think it's in the example files but not the docs themselves. Also I believe passing in a None value will have the same effect as the "none" string but I'll confirm that as well.

**Comment by MerrimanInd** [comment]
Documentation updates are done, should be live soon!
